// app/layout.tsx (or src/app/layout.tsx)
import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/nav/header";
import Footer from "@/components/shared/nav/footer";
import { ThemeProvider } from "@/lib/theme-context";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins", // note: this exact name is used by CSS
  weight: ["300", "400", "500", "600", "700"], // optional
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${poppins.variable} ${inter.variable}`}>
      <head>
        <script
          async
          crossOrigin="anonymous"
          src="https://tweakcn.com/live-preview.min.js"
        />
      </head>
      <body className="antialiased">
        <ThemeProvider >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
